Issue 2 score authentication for ck board
encorelab/SCORE-API pull request #6
Opened 2022-07-09 00:35 UTC by geoffreykwan

Note: Make sure to go into application-dockerdev.properties and set values for the new CK Board properties. The ck_board_sso_secret_key can be anything as long as you use the same one in the ck-board .env file.

```
ck_board_url=http://localhost:4201
ck_board_sso_secret_key=VV5jf6rXt4zrbBuH
```

## Changes

- Added SSO endpoint for CK Board to access
- Handled redirect url when accessing a CK Board url using SCORE authentication
- Added CK Board properties to application.properties

## Test

- CK Board can use SCORE for authentication
- CK Board is properly redirected to the CK Board url that you originally tried to access before signing in to SCORE (for example if you are signed out of CK Board and then you try to access a board directly like http://localhost:4201/project/e347aab0-6623-4ffb-8950-191192956cac/board/eaee497d-3730-451f-a939-a4e5416a9d96)

2022-08-10 01:54 UTC, hirokiterashima requested changes
Works well. Added minor code improvement suggestion inline.

Can we also add some unit tests for CkBoardSsoController.ckBoardSsoLogin()?

2022-08-10 01:54 UTC, hirokiterashima commented on src/main/java/org/wise/portal/presentation/web/controllers/CkBoardSsoController.java
> +import java.net.URISyntaxException;
Unused
```suggestion
```

2022-08-15 15:15 UTC, hirokiterashima approved these changes
Looks good to me.

2022-08-16 00:55 UTC, JoelWiebe approved these changes

2022-08-17 14:51 UTC, merged